version: 2

project_name: quark-mcp

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: quark-mcp
    ldflags:
      - -s -w -X github.com/chiehw/quark-mcp/internal/version.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

release:
  extra_files:
    - glob: ./mcpb-dist/*.mcpb

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
